# Generated by Django 3.2 on 2023-04-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230424_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='recipesingredients',
            name='units',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='units',
            field=models.CharField(default=None, max_length=11, verbose_name='единицы измерения'),
            preserve_default=False,
        ),
    ]
