# Generated by Django 3.2 on 2023-04-27 19:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_rename_quantity_recipesingredients_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Subscribe',
        ),
    ]
