# Generated by Django 3.2 on 2023-05-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230502_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Название рецепта', related_name='recipes', through='recipes.RecipesIngredients', to='recipes.Ingredient', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Теги', related_name='recipes', through='recipes.RecipesTags', to='recipes.Tag', verbose_name='Теги'),
        ),
    ]
