# Generated by Django 3.2 on 2023-05-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20230504_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Название рецепта', through='recipes.RecipeIngredient', to='recipes.Ingredient', verbose_name='Рецепт'),
        ),
    ]
