version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - foodgram_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
#    build:
#      context: ../backend/api_foodgram
#      dockerfile: Dockerfile
    image: anf16f/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/api_foodgram/backend_static/
      - media_value:/app/api_foodgram/backend_media/
    depends_on:
      - db
    env_file:
      - ../backend/api_foodgram/api_foodgram/.env
  frontend:
    image: anf16f/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - openapi-schema.yml/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    depends_on:
      - db
      - backend
volumes:
  static_value:
  media_value:
  foodgram_data:
